MaxBank/Models/Account.cs
using MaxBank.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MaxBank.Models
{
    public class Account
    {
        public int Id { get; set; }
        public int Balance { get; set; }


        public string Transfer(int TransferToAccountNumber, int Amount)
        {
            if(this.Balance < Amount)
            {
                return "Insuffiecient amount, transfer failed.";
            }
            var accToTransferTo = BankRepository.GetAccountFromAccountNumber(TransferToAccountNumber);
            if(accToTransferTo == null)
            {
                return "Account not found with account number: " + TransferToAccountNumber;
            }
            this.Balance -= Amount;
            accToTransferTo.Balance += Amount;

            return "Transfer succeded, new balance is: "+this.Balance+"Kr";
        }
    }
}

MaxBank/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MaxBank.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Account> Accounts { get; set; }
    }
}

MaxBank/Models/ErrorViewModel.cs
using System;

namespace MaxBank.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MaxBank/ViewModels/BankActionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace MaxBank.ViewModels
{
    public class BankActionViewModel
    {
        [DisplayName("Accountnumber")]
        public int AccountId { get; set; }
        [DisplayName("Amount")]
        public int Amount { get; set; }

        public string Message { get; set; }
    }
}

MaxBank/ViewModels/TransferViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace MaxBank.ViewModels
{
    public class TransferViewModel
    {
        [DisplayName("From Account number")]
        public int FromAccountId { get; set; }
        [DisplayName("To Account number")]
        public int ToAccountId { get; set; }
        [DisplayName("Amount")]
        public int Amount { get; set; }

        public string Message { get; set; }
    }
}

MaxBank/Controllers/BankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MaxBank.Data;
using MaxBank.Models;
using MaxBank.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace MaxBank.Controllers
{
    public class BankController : Controller
    {
        private readonly BankRepository _bankRepository;
        
        public BankController(BankRepository bankRepository)
        {
            _bankRepository = bankRepository;
        }

        public IActionResult Index()
        {
            var vm = new BankActionViewModel();

            return View(vm);
        }

        [HttpPost]
        public IActionResult Index(string button, int accountId, int amount)
        {
            var vm = new BankActionViewModel();
            var customer = BankRepository.Customers.FirstOrDefault(c => c.Accounts.Select(a => a.Id == accountId).First());

            if (customer != null)
            {

                var balance = customer.Accounts.FirstOrDefault(a => a.Id == accountId).Balance;

                if (button == "Withdraw")
                {
                    if (amount > balance)
                    {
                        vm.Message = "Withdraw failed! You cannot withdraw that amount!";
                        return View(vm);
                    }

                    _bankRepository.Withdraw(amount, accountId);

                    vm.Message = "Withdraw succeeded, your new balance is: " + customer.Accounts.FirstOrDefault(a => a.Id == accountId).Balance;

                }
                else if (button == "Deposit")
                {

                    _bankRepository.Deposit(amount, accountId);
                    vm.Message = "You deposited " + amount + " your new balance is: " + customer.Accounts.FirstOrDefault(a => a.Id == accountId).Balance;
                }
            }
            else
            {
                vm.Message = "Wrong account number!";
            }


            return View(vm);
        }

        [HttpGet]
        public IActionResult TransferMoney()
        {
            return View("TransferMoney");
        }

        [HttpPost]
        public IActionResult TransferMoney(TransferViewModel vm)
        {
            if(!ModelState.IsValid)
            {
                vm.Message = "Failed to transfer, please check your inputs.";
                return View("TransferMoney", vm);
            };
            var acc = BankRepository.GetAccountFromAccountNumber(vm.FromAccountId);
            if (acc == null)
            {
                vm.Message = "Wrong account information. No accounts found with account number: " + vm.FromAccountId;
            }
            else
            {
                vm.Message = BankRepository.GetAccountFromAccountNumber(vm.FromAccountId).Transfer(vm.ToAccountId, vm.Amount);
            }

            return View("TransferMoney",vm);
        }
    }
}

MaxBank/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MaxBank.Models;
using MaxBank.Data;

namespace MaxBank.Controllers
{
    public class HomeController : Controller
    {
        private readonly BankRepository _bankRepository;

        public HomeController(BankRepository bankRepository)
        {
            _bankRepository = bankRepository;
        }
        
       
        public IActionResult Index()
        {
            
            return View(BankRepository.Customers);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MaxBank/Views/Bank/Index.cshtml
@model MaxBank.ViewModels.BankActionViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Hello please withdraw or deposit some money</h2>
<br />
<br />
@if (Model.Message == "Wrong account number!" || Model.Message == "Withdraw failed! You cannot withdraw that amount!")
{
    <h4 style="font-weight: bold; color:red">@Model.Message</h4>

}
else if (Model.Message != null)
{
    <h4 style="font-weight: bold; color:lawngreen">@Model.Message</h4>
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AccountId" class="control-label"></label>
                <input asp-for="AccountId" class="form-control" name="accountId" />
                <span asp-validation-for="AccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" name="amount" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Withdraw" class="btn btn-danger" name="button" />
                <input type="submit" value="Deposit" class="btn btn-success" name="button" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MaxBank/Views/Bank/TransferMoney.cshtml
@model MaxBank.ViewModels.TransferViewModel

@{
    ViewData["Title"] = "Transfer";
}

<h2>Transfer</h2>

<hr />
@if (Model != null)
{
    <h3 style="color:blue">@Model.Message</h3>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="TransferMoney">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FromAccountId" class="control-label"></label>
                <input asp-for="FromAccountId" class="form-control" />
                <span asp-validation-for="FromAccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToAccountId" class="control-label"></label>
                <input asp-for="ToAccountId" class="form-control" />
                <span asp-validation-for="ToAccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MaxBank/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MaxBank/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MaxBank/Views/Home/Index.cshtml
@model List<Customer>;

<h1>Max Bank</h1>
<div>
    @foreach (var customer in Model)
    {
        <div style="border:2px solid black; width: 300px; display:inline-block;">
            <h5>Namn: @customer.Name</h5>
            <p>Kundnummer: @customer.Id</p>
            <p>Konton: </p>
            <div style="border:1px solid black">
                @foreach (var account in customer.Accounts)
                {
                    <h6>Kontonummer: @account.Id</h6>
                    <p>Saldo: @account.Balance</p>
                }
            </div>
        </div>
    }
</div>

MaxBank/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnv
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@hostingEnv.EnvironmentName</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">@hostingEnv.EnvironmentName Max Bank</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Bank" asp-action="Index">Withdraw/Deposit</a></li>
                    <li><a asp-area="" asp-controller="Bank" asp-action="TransferMoney">Transfer</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MaxBank</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>